server:
  port: 8080

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

spring:
  profiles:
    active: local



encryption:
  aes-key: 1234567890123456
