server:
  port: 8080
cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"
encryption:
  aes-key: 1234567890123456

spring:
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5332/cardManagement
    username: levantos
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
      boot:
        allow_jdbc_metadata_access: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml

